// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMrmIZGR76iatwihQGlK3NdSZlUVdGPA',
    appId: '1:20867615796:android:b3d4fb86af6c0acd120e61',
    messagingSenderId: '20867615796',
    projectId: 'ayadymisr-12eac',
    storageBucket: 'ayadymisr-12eac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh0lRX-H4IbCLvKO0xGi4Ej-xmSNRhdRk',
    appId: '1:20867615796:ios:7da499bf7e05c7d2120e61',
    messagingSenderId: '20867615796',
    projectId: 'ayadymisr-12eac',
    storageBucket: 'ayadymisr-12eac.appspot.com',
    androidClientId: '20867615796-qm139gvgvmmm67esprq0l32t02t2tq2j.apps.googleusercontent.com',
    iosClientId: '20867615796-cngf5sj1tosvm221318jthg8u3p2skhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayadymisr',
  );
}
