// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgYEXcedL2M9GjLuVsvBohi56y1SJ4uKc',
    appId: '1:279185412002:android:6226635faf2ea7477b6cfb',
    messagingSenderId: '279185412002',
    projectId: 'agrimisr-b9223',
    storageBucket: 'agrimisr-b9223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgQrw3MQdDVZlt8vGc0Ukl8NZo-sYV-4',
    appId: '1:279185412002:ios:768b59a0532a2bea7b6cfb',
    messagingSenderId: '279185412002',
    projectId: 'agrimisr-b9223',
    storageBucket: 'agrimisr-b9223.appspot.com',
    androidClientId: '279185412002-t001agfm6duif41bcfh4mjqm78f2gggl.apps.googleusercontent.com',
    iosClientId: '279185412002-d4er9fohek2h7hsh92p5u9bj2psi494s.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrimisr',
  );
}
